### PR TITLE
Rename `services` command to `systemd_services`

### PR DESCRIPTION
**Pull request by nissou91**

### CODE REVIEW

**Comment by fblackburn1** [comment]
Can you describe why this renaming?
Is it not redundant to have `sysconfd` prefix in sysconfd client?

**Comment by nissou91** [comment]
> Can you describe why this renaming? Is it not redundant to have `sysconfd` prefix in sysconfd client?

Because in the two tickets that I have, I reorganised the structure to have something like `plugins/sysconfd_services/services.py` and `plugings/hosts/services.py`, I think it is better to have these two files within the plugin itself (they contain the functions defined respectively within `/nodules/services.py` and `/modules/resolvconf.py`). So I thought that is is better to rename the plugin to `sysconfd_services`

**Comment by fblackburn1** [comment]
> > Can you describe why this renaming? Is it not redundant to have `sysconfd` prefix in sysconfd client?
> 
> Because in the two tickets that I have, I reorganised the structure to have something like `plugins/sysconfd_services/services.py` and `plugings/hosts/services.py`, I think it is better to have these two files within the plugin itself (they contain the functions defined respectively within `/nodules/services.py` and `/modules/resolvconf.py`). So I thought that is is better to rename the plugin to `sysconfd_services`

Well I'll leave it to the reviewer, but I don't think it's a good idea to have `plugins/sysconfd_services` it is redundant and doesn't make any sense while you are already in the sysconfd context. Because `services` refer to [unix system `service](https://wiki.debian.org/systemd/Services) (i.e. systemctl command), *not anything to sysconfd*

**Review by sduthil — CHANGES_REQUESTED** [review]
We cannot change the API in this branch: the `/services` API is needed by other services, and breaking the API would break other services. Renaming can happen in another branch, but not here. And yes, I totally agree that a `/services` API is a terrible name for what we're doing.

**Comment by nissou91** [comment]
> We cannot change the API in this branch: the `/services` API is needed by other services, and breaking the API would break other services. Renaming can happen in another branch, but not here. And yes, I totally agree that a `/services` API is a terrible name for what we're doing.

Okay, I will close this PR then since it is not needed anymore.

**Pull request closed without merging**
